# Generated by Django 5.2.7 on 2025-10-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_authorityprofile_reputation_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorityprofile",
            name="reputation_score",
        ),
        migrations.RemoveField(
            model_name="authorityprofile",
            name="total_reports",
        ),
        migrations.RemoveField(
            model_name="authorityprofile",
            name="verified_reports",
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="reputation_score",
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="total_reports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="verified_reports",
            field=models.IntegerField(default=0),
        ),
    ]
