# Generated by Django 5.2.7 on 2025-10-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_user_id_a4dd5c_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_created_e4c995_idx",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="user",
            new_name="recipient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="read_at",
        ),
        migrations.AddField(
            model_name="notification",
            name="related_object",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("incident_reported", "Incident Reported"),
                    ("incident_assigned", "Incident Assigned"),
                    ("incident_verified", "Incident Verified"),
                    ("incident_resolved", "Incident Resolved"),
                    ("incident_pending_assignment", "Incident Pending Assignment"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="notification",
            table=None,
        ),
    ]
