# Generated by Django 5.2.7 on 2025-10-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
        ("users", "0004_authorityprofile_document_citizenprofile_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="incident",
            name="incidents_created_bc994b_idx",
        ),
        migrations.RemoveIndex(
            model_name="mediaaccess",
            name="media_acces_media_h_ee9f76_idx",
        ),
        migrations.RemoveIndex(
            model_name="mediaaccess",
            name="media_acces_inciden_cf4b7b_idx",
        ),
        migrations.RemoveIndex(
            model_name="mediaaccess",
            name="media_acces_accesse_e03f9f_idx",
        ),
        migrations.RemoveField(
            model_name="mediaaccess",
            name="media_file",
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Verified"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="incidentmedia",
            name="file_size",
            field=models.PositiveIntegerField(help_text="File size in bytes"),
        ),
        migrations.AlterField(
            model_name="mediaaccess",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_access",
                to="incidents.incident",
            ),
        ),
        migrations.AlterField(
            model_name="mediaaccess",
            name="media_house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="users.mediahouseprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["region"], name="incidents_region_d1b641_idx"),
        ),
        migrations.AlterModelTable(
            name="mediaaccess",
            table="media_access",
        ),
    ]
