# Generated by Django 5.2.7 on 2025-10-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_authorityprofile_reputation_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorityprofile",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="authority_docs/"),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="mediahouseprofile",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="media_docs/"),
        ),
    ]
