# Generated by Django 5.2.7 on 2025-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorityprofile",
            name="reputation_score",
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name="authorityprofile",
            name="total_reports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="authorityprofile",
            name="verified_reports",
            field=models.IntegerField(default=0),
        ),
    ]
